### PR TITLE
Disable option display_errors by default

### LINKED ISSUE #129: Readme is wrong
Given examples don't work.

For example: https://github.com/tarantool/http/blob/master/README.md#working-with-stashes

```lua
httpd = box.httpd.new('127.0.0.1', 8080)
...
```

There is no such thing as box.httpd.

### LINKED ISSUE #135: URL in README.md is broken
https://raw.githubusercontent.com/tarantool/http/master/rockspecs/http-scm-1.rockspec
404

### PR DESCRIPTION
**Pull request by ligurio**
Fixes https://github.com/tarantool/security/issues/8
Fixes #129 
Fixes #135 
Fixes a CMake warnings for passed package names

~~**PR depends on https://github.com/tarantool/http/pull/141**~~

NOTE: Issue https://github.com/tarantool/security/issues/8 must be closed manually after merging.

### CODE REVIEW

**Review by DifferentialOrange — APPROVED** [review]
I think it is worth to duplicate commit messages (like the one about Django) additional info to PR description since public users do not have access to tarantool/security ticket.

**Comment by ligurio** [comment]
> I think it is worth to duplicate commit messages (like the one about Django) additional info to PR description since public users do not have access to tarantool/security ticket.

It was already there, except link to site about django. Well, added it too.

**Comment by ligurio** [comment]
Screenshot from 2021-11-02 15-47-39

**Comment by DifferentialOrange** [comment]
> > I think it is worth to duplicate commit messages (like the one about Django) additional info to PR description since public users do not have access to tarantool/security ticket.
> 
> It was already there, except link to site about django. Well, added it too.

I mean this description
image

**Comment by ligurio** [comment]
>>> I think it is worth to duplicate commit messages (like the one about Django) additional info to PR description since public users do not have access to tarantool/security ticket.

>> It was already there, except link to site about django. Well, added it too.

> I mean this description

What's a point to publish a description of security issue before fixing it?

**Comment by ligurio** [comment]
@DifferentialOrange I added to PR description all issues that fixed by this PR. Also removed commits related to #137, so we can merge these commits without waiting of fix for #137.

File: http/server.lua [hunk 1]
```diff
@@ -859,6 +859,10 @@ local function process_client(self, s, peer)
             hdrs['content-length'] = #body
         end
 
+        if hdrs['content-type'] == nil then
+            hdrs['content-type'] = 'text/plain; charset=utf-8'
```
Comment (Totktonada) [inline http/server.lua:863]: Nit: It is 'text/plain; utf-8' in the commit message, looks as the typo.

File: http/server.lua [hunk 2]
```diff
@@ -1290,6 +1290,7 @@ local exports = {
             log_requests        = true,
             log_errors          = true,
             display_errors      = true,
+            keepalive_disable   = {},
```
Comment (Totktonada) [inline http/server.lua:1297]: It does not look related to this commit.

File: http/server.lua (hunk 1 above)
Comment (Totktonada) [reply http/server.lua:863]: I would also leave several words why default content type may be important from security point of view.

**Review by Totktonada — APPROVED** [review]
Looks good except several minor nits. Feel free to push after fixes.

File: http/server.lua (hunk 1 above)
Comment (ligurio) [reply http/server.lua:863]: Fixed.

File: http/server.lua (hunk 2 above)
Comment (ligurio) [reply http/server.lua:1297]: True, fixed.

**Comment by ligurio** [comment]
> I would also leave several words why default content type may be important from security point of view.

Updated commit message.
